name: CI

on: [push]

env:
  CI: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        node-version: [12.x, 10.x]
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: actions/cache@v1.1.2
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: npx prettier --check "src/**"
      # Prettier for some reason reports that the formatting is off on Windows.
      # Since a single check is sufficient for code formatting, we skip it there:
      if: runner.os != 'Windows'
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: code-coverage-report
        path: coverage
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dist
        path: dist
  release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.1.0
    - name: Prepare for publication to GitHub Packages
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@inrupt'
    - name: Prepare prerelease version
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com
        # Make sure the prerelease is tagged with the branch name, and that they are sorted by build:
        npm version prerelease --preid=${GITHUB_REF#refs/heads/}-$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER
    - run: npm ci
    - run: npm publish --tag "${GITHUB_REF#refs/heads/}"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        echo "Package published. To install, run:"
        echo ""
        echo "    npm_config_registry=https://npm.pkg.github.com/inrupt npm install @inrupt/lit-solid-core@${GITHUB_REF#refs/heads/}"
        echo ""
        echo "(You might first need to log in with \`npm login --registry=https://npm.pkg.github.com\`.)"